
name: vesta
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  lucide_icons: ^0.257.0

  # State Management
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

  # Navigation
  go_router: ^10.0.0

  # Networking
  dio: ^5.3.2
  
  # Local Storage
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
