"""add google token status to user

Revision ID: 2b1c06cfe7d0
Revises: 52f305bef49d
Create Date: 2026-07-15 22:38:25.757503

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b1c06cfe7d0"
down_revision: str | Sequence[str] | None = "52f305bef49d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_token_status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "google_token_status")
    # ### end Alembic commands ###
