"""Add summary field

Revision ID: 2bf3bbddc881
Revises: d2b2c637e350
Create Date: 2026-02-23 22:03:45.657115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf3bbddc881'
down_revision: Union[str, Sequence[str], None] = 'd2b2c637e350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'summary')
    # ### end Alembic commands ###
