"""create_user_facts_table

Revision ID: 52f305bef49d
Revises: 2bf3bbddc881
Create Date: 2026-07-08 09:28:53.364679

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52f305bef49d"
down_revision: str | Sequence[str] | None = "2bf3bbddc881"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_facts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fact_content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_facts_user_id"), "user_facts", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_facts_user_id"), table_name="user_facts")
    op.drop_table("user_facts")
    # ### end Alembic commands ###
