"""Add city name to user table

Revision ID: d2b2c637e350
Revises: 451d9f9c7aae
Create Date: 2026-02-15 11:19:33.617348

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2b2c637e350"
down_revision: str | Sequence[str] | None = "451d9f9c7aae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("city_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "city_name")
    # ### end Alembic commands ###
