"""Add google auth fields

Revision ID: e30bc4d09687
Revises: 02d8062b187a
Create Date: 2026-01-19 17:01:54.416558

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e30bc4d09687"
down_revision: Union[str, Sequence[str], None] = "02d8062b187a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("google_refresh_token", sa.String(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "is_daily_summary_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_daily_summary_enabled")
    op.drop_column("users", "google_refresh_token")
    # ### end Alembic commands ###
